### ISSUE TITLE
Reflecting number 1 in status charts

### ISSUE THREAD

**Issue by chaosarium** [HugoFara/lwt#11]
<img width="78" alt="Capture d’écran 2022-02-07 à 21 55 50" src="https://user-images.githubusercontent.com/38693485/152812535-a1f13be1-0698-4893-94d0-e38672d54f8c.png">

log(1) is technically 0 so this is expected with a log scale. I wonder if anything needs to be done so that the number 1 is reflected on the chart. 

I think I might want to look into this. Is there any way I can assign myself for this issue?

**Comment by HugoFara** [comment]
Hi!

Normally to contribute to a repository, it is only done through pull requests, the fact that I assigned you only meant that you would be notified for any update to this thread.

Otherwise, I have conducted a big refactoring of ``edit_texts.php``, so I used this occasion to edit the log scale, solving the issue. Changes have been pushed to master.

My solution was to increment the index by 1: a log scale should always start at 1, it has a small impact on the scale visually, but things seem to work fine.

Let me know if you have any comment! I will close this issue with the next release, which should come very soon!
