### ISSUE TITLE
Misc. warnings

### ISSUE THREAD

**Issue by HenryWales** [HugoFara/lwt#121]
After updating settings, I get:

Warning: Undefined array key "set-tts" in C:\xampp\htdocs\lwt\settings.php on line 104

After creating a new multi-term word using the "new term" button on top of a text page:

Warning: Undefined array key "query" in C:\xampp\htdocs\lwt\inc\session_utility.php on line 2980

**Comment by HugoFara** [comment]
Hi!

I tried to reproduce the warning following your description but unfortunately, nothing out of the ordinary happened (I got no warnings). Can you confirm that you are using LWT 2.8.1?

I also looked at the source code for "set-tts", maybe because it is a checkbox a warning appears. Can you replace line 100 of ``settings.php`` by
```php

        saveSetting(
            'set-tts',
            (
                array_key_exists('set-tts', $_REQUEST) && 
                (int)$_REQUEST['set-tts'] ? 
                1 : 0
            )
        );
        ```

As I cannot reproduce the issue I must rely on you here!

As a side note, you can deactivate warnings in XAMPP settings if it's an issue for you, they are intended for developers anyway.

**Comment by HugoFara** [comment]
Hi! Thank you for the image, I was able to reproduce and fix the bug. It came with LWT 2.8.0 when I changed the dictionary URL standard.

I'm also fixed the bug in the settings, thanks for your help!

I am finishing some work on the dev branch, and I should push everything to master by the end of the week!
