### ISSUE TITLE
Phrase select broken?

### ISSUE THREAD

**Issue by chaosarium** [HugoFara/lwt#21]
In the original LWT version, one can select phrases by first clicking and holding on a word and dragging. This seems broken in the current version.

A screenshot of the drag and multiselect feature:

<img width="340" alt="Capture d’écran 2022-02-27 à 17 59 11" src="https://user-images.githubusercontent.com/38693485/155877894-89ec9053-c45a-4e2b-bb13-94f679ae2e3c.png">

**Comment by HugoFara** [comment]
Hi, 

I never tried that feature, so it may have got broken long ago. I will inspect this in a latter time, thanks for signaling it!

**Comment by Kit1205** [comment]
Hi,
I've been testing some things on the Version 2.3.0.
It is still possible to select and translate the phrases with the long click and drag method. However the created expression is in no way marked in the readig text, nor does the the little number in square brackets appear in front of it, as the original documentation suggests. (example down below)
![image](https://user-images.githubusercontent.com/106033711/169712966-35746405-7439-4b1f-8c5b-b5b5252a5212.png)

This is when the learning phrase was created on the 2.3.0. version. (the expression is located in the unblurred line):
![chrome_A0Vl9VGbtR](https://user-images.githubusercontent.com/106033711/169713140-1119b111-7364-4791-b5c8-135249d9d4ef.png)

**Comment by HugoFara** [comment]
Wow thank you for this hint! I have been focused on more troublesome bugs until release 2.4.0, and honestly I had no time to tackle this issue.

As I just fixed Japanese with the latest release, let's continue with Asian languages, Korean is a good use case for "multi-word" selection, because it shows that it is not a cool feature that is broken (as I considered it), but a real bug that make some languages unusable. I cannot tell how long it will be until the next release, but the more help I receive, the sooner it will come!

**Comment by Kit1205** [comment]
No worries! :) 

Out of curiosity, I also checked if this bug was present in the previous versions that were released - and yeah it's been present since the first altered release (2.1.0 I believe).

Additionally, I checked out the release you did today and found some new info, _I think_. The colour of the first word of the selected phrase is changed to red and it seems to be happening about 50-60% of the time when I try creating a new learning expression.

![term_example](https://user-images.githubusercontent.com/106033711/169887811-61832897-d989-4fbc-a2d6-573962aa8ad2.png)

These are the three term (expression) examples I made in the text. 
Respectively: 
1. 꽉 자
2. 마음이 불편해요
3. 한자로 아루어진 

In other cases the expression still stays unmarked. 
I'll keep investigating, maybe I'll stumble on something else that would help out.
Thanks a lot for all your work on this project!

**Comment by HugoFara** [comment]
Hello!

I have been working *really* hard to fix this (seriously, it two me two months), and finally things seem not so bad with release 2.5.0.

Basically, everything was either broken or a mess, so it it was really frustrating when you can't even tell if a code behavior is expected or not. Now, things are much better, so I can finally detail what was wrong.

So here are the problems I ran through, enjoy :smile: 

1. Registering multi-words was awfully complex: basically bad code that was difficult to parse into functions. I had to carefully craft the class ``Term`` that is expected to become one of the major objects of LWT.
2. Server-side code for inserting expressions was broken *for Japanese only*. Yep, that is a kind of bug that was confusing.
3. Words count for Japanese (again) was broken, leading to visual glitches.
4. Code for selecting the multi-words to hide and show (in HTML) was wrong, it seems to date back from the official LWT.
5. The code for displaying multi-words broken: it was causing multi-words to appear in red as in [your comment](https://github.com/HugoFara/lwt/issues/21#issuecomment-1135037712) #issuecomment-1135037712 ). I mistakenly delete white spaces in 2.0.1-fork.
6. Of course, the JavaScript part was equally broken, so the visual display of new multi-words was not successful, as the code was calling undefined global variables.

Now, some bugs may remain, but I think most of the job is done. Thank you for all your help, it allowed me to sort things out and to stay motivated!
