### ISSUE TITLE
Mecab for Japanese can't parse texts

### ISSUE THREAD

**Issue by rc-ops** [HugoFara/lwt#23]
Hi! 
I've tried to use LWT in the past but due to the lack of Japanese tokenization it just wasn't worth the trouble and since then I've been looking for an alternative. When I found this fork I and I saw that it had mecab support, I decided to try again, but haven't been able to read anything so far.

**Describe the bug**
After installing EasyPHP Devserver 17 and following the instructions [here](https://github.com/HugoFara/lwt/blob/master/docs/langsetup.md), then setting LWT to use _mecab_ in _RegExp Word Characters_ field, whenever I try to import a text I get an error.

```
Fatal Error in SQL Query: LOAD DATA LOCAL INFILE 'C:\\Users\\USER\\AppData\\Local\\Temp/tmpti.txt' INTO TABLE temptextitems2 FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n' (@c,@e,@f) SET TiSeID = if(@g=2 or (@f="7" and @c="EOS"), @s:=@s+(@d:=@h)+1,@s), TiCount = (@d:=@d+CHAR_LENGTH(@c))+1-CHAR_LENGTH(@c), TiOrder = if( CASE WHEN @f = '7' THEN IF(@c="EOS",(@g:=2) AND (@c:="¶"), @g:=2) WHEN LOCATE(@e,'267') THEN @g:=@h ELSE @g:=1 END IS null, null, @a:=@a+IF((@i=1) AND (@g=1), 0, 1)+IF((@i=0) AND (@g=0), 1, 0)), TiText = @c, TiWordCount= CASE WHEN (@i:=@g) IS NULL THEN NULL WHEN @g=0 THEN 1 ELSE 0 END

Error Code & Message: [7890] Can't find file 'C:\Users\USER\AppData\Local\Temp/tmpti.txt'.
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Import a Japanese text and set the language accordingly, doesn't matter if you upload or paste it
2. Get an error

**Expected behaviour**

1. Get a message saying that the import was done and be able to read the imported text as a result.

**Screenshots**
Language configuration
![chrome_adQcMWNHus](https://user-images.githubusercontent.com/72221896/156939226-822b1df4-a5a9-47a7-9710-a6db6d35d07e.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2 and Windows 10 20H2
 - Browser: Chromium 97.0.4692.71
 - EasyPHPDevserver-17 PHP 7.1.3
 - XAMPP (didn't work either)

**Additional context**
I've noticed that if I create the above file **tmpti.txt**, LWT removes the file and returns the same error message. Perhaps it has something to do with backslashes on windows? Shouldn't the path be C:\Users\USER\AppData\Local\Temp\tmpti.txt instead of C:\Users\USER\AppData\Local\Temp/tmpti.txt ? Well, I don't know any PHP, so... :P
I tried a while ago to make it work on my Arch machine but I couldn't make it connect to the database so I gave up. 
I'm also uploading the Backtrace
[Backtrace.txt](https://github.com/HugoFara/lwt/files/8193383/Backtrace.txt)

**Comment by HugoFara** [comment]
Hi!

Sorry for the delay, I won't be able to help much during those week.

This issue seems related to Windows (with Linux things run smoothly). Could you try to replace ``$file_name = sys_get_temp_dir() . "/" . $tbpref . "tmpti.txt";`` by ``$file_name = sys_get_temp_dir() . "\\" . $tbpref . "tmpti.txt";`` in ``inc/database_connect.php``, line 668?

Hope this will help before I push a better version.

Could you also check if you have [installed MeCab](https://taku910.github.io/mecab/#install)?

Moreover, you can try the same with the official LWT, type MeCab in the "RegExp Word Character".

**Comment by HugoFara** [comment]
> I tried a while ago to make it work on my Arch machine but I couldn't make it connect to the database so I gave up.

Would you like to open an issue or start a new discussion?

**Comment by rc-ops** [comment]
Hi!
I've reinstalled MeCab and made sure to add it to my path. 
```
C:\Program Files (x86)\MeCab\bin
C:\Program Files (x86)\MeCab\sdk
```
I was able to reparse the text. However, here's the result:
![chrome_S1TU6MNa33](https://user-images.githubusercontent.com/72221896/157769580-181281b0-8acb-454c-aac5-d1555f6c26d0.jpg)

**Comment by rc-ops** [comment]
> Would you like to open an issue or start a new discussion?

For now, I'm gonna give it a spin on Ubuntu, it's just easier to play with servers and databases there, since I don't have to compile specific versions of php from source. Or extensions... I'll let you know how it goes.

**Comment by HugoFara** [comment]
Hello!

Sorry for this long time without answer. I had little to no time, and no computer running Windows, so I was unable to address your issue.

But this has changed, I have been able to reproduce and solve your successive troubles, so here is a recap:
- [7890] Can't find file 'C:\Users\USER\AppData\Local\Temp/tmpti.txt': LWT could not find the path of MeCab on your system, so it was unable to output the file "tmpti.txt". As the existence of MeCab was not checked, no error were raised on the server side, leading to this scrappy behavior.
  - I added several installation path for MeCab on Windows.
  - LWT now checks if MeCab exists before using it.
- Regarding the bad parsing of japanese texts, PHP was silently converting the end-of-line character "\n" to "\r\n". It took me a good day to figure this out. I tried to fix this inconsistency across the files, but it may reappear somewhere, so let me know if you spot any problem!


The fix is pushed on the ``dev`` branch, and as it is a pretty important one I should release LWT version 2.4.0 in a few days. Please wait until then!
