### ISSUE TITLE
Website isn't responsive on mobile devices

### ISSUE THREAD

**Issue by nghiaphamtm** [HugoFara/lwt#27]
Hi,
When I resize the window on the computer, the website respond very well. But on my phone, it's not responsive as when I resize window on the computer. 

**Here is the screenshot on computer.**
<img src="https://user-images.githubusercontent.com/102361929/163382550-6f865e92-473a-4096-a9c8-c50aaa80c605.png" width="350" height="500">

**And here is the screenshot on my phone.**
<img src="https://user-images.githubusercontent.com/102361929/163379497-741e60a1-5337-46fa-9a2f-ecf417f1a154.png" width="350" height="500">

**Comment by HugoFara** [comment]
Thanks for signaling it!

The mobile version of LWT is a feature still in progress, so they are various interface issues. I may fix the main menu in the next release (~1 week), but similar problems will remain. It will take a much more work to make everything pretty on phone, so that should come with iterations dedicated to phone exclusively (~2 months).

**Comment by HugoFara** [comment]
Hi! Sorry for the long wait, I investigated further the issue, and it seems to be harder to solve than expected. The original dev created LWT with a specific screen size in mind (900px), I changed that in a new [responsive branch](https://github.com/HugoFara/lwt/tree/responsive), but it actually makes things harder to use, so I am not merging now, but you can still try and test out, if I find an easy way to use a responsive design, why not, otherwise it may not be implemented at all.

**Comment by HugoFara** [comment]
Hi again! It was a long way to go, but it works in the end, so I pushed to master. Currently, only the default theme supports the responsive design, I will roll update to themes progressively, of course I accept an pull request :smile:
