### ISSUE TITLE
Add sounds

### ISSUE THREAD

**Issue by HugoFara** [HugoFara/lwt#3]
Sounds are often a good way to make an application more lively.

Open source sounds are necessary, but that should not be a problem.

**Comment by chaosarium** [comment]
I noticed the same problem as I went in and tried to fix things for my personal use. It seems like that `tts.php` in the original versional is responsible for making sounds when words are clicked, but the Google Translate API is no longer working (I think you might have noticed that I removed calls to tts.php in my fork, which you later forked). I tried to fix the issue but, since I don't know PHP, I made little progress.

So far I have been using MacOS's built in text-to-speech after manually selecting the text, which produces serviceable sound and works offline. I wonder if there is a way to invoke the system speech synthesizer from the browser. I thought [say.js](https://github.com/Marak/say.js/) might be an option but didn't have time to look into integrating it to LWT.

As of open source sounds, I don't think it would be necessary if the system speech synthesizer suffice. I assume you are talking about adding an open source sound library?

I didn't have time to experiment with using the system synthasizer since my last commit in August, but I could try if you think this is a good idea.

**Comment by chaosarium** [comment]
As far as I am aware, the current version already implemented a "Read in browser" button that reads the whole text in the browser. But since I have audio for texts already, I think it's more helpful to have speech synthesis for individual words. Or am I missing something...

**Comment by HugoFara** [comment]
I was more thinking of sounds when doing tests for example, a "success" sound is rewarding, which help learning.

A text-to-speech feature for individual word is also a good idea. In fact modern browsers already ship this functionality with JS, so there is no need to install anything here :) 

Concerning the file ``tts.php``, I don't think to re-use it again, because it is simply unnecessary.

As there is no priority here, I do not have a date for this feature but I am welcome to any pull request! If you want to experiment a bit, you can try to reproduce the "Read in browser" functionality  in ``do_test_test.php``.

**Comment by chaosarium** [comment]
Hi! 

I did manage to implement a new tts.php that works with the SpeechSynthesis API in modern browsers on my fork (mostly in [this commit](https://github.com/chaosarium/lwt/commit/8637e92a593532d7a68e6dc150deeda9bef57e6e)). I took a look at your version but realised something breaks when migrating my lwt database, which I think I will open another issue with details. Hopefully I can open a pull request in the future when things are figured out :)

**Comment by HugoFara** [comment]
Hi!

I have read your commits, There are a few steps we need to take before any pull request, so I created an issue [on your fork](https://github.com/chaosarium/lwt/issues/2).

I don't remember changing database calls, so that may be an issue related to the official LWT, it worth opening a separate issue.

I'm also implementing sounds for tests, you can listen to [sounds folder on dev branch](https://github.com/HugoFara/lwt/tree/dev/sounds), so we may close this issue soonner tanh expected.

**Comment by HugoFara** [comment]
For records, I implemented two sounds systems in [release 2.2.0](https://github.com/HugoFara/lwt/releases/tag/v2.2.0).

- "Success" and "Failure" sounds that play during tests. They are compatible with themes, so they can be customized.
- A text-to-speech reading *for tests only*. This is an optional feature.

How is it going on your side @chaosarium ? Your commits on ``tts.php`` tackle a broader issue, so your work can still be implemented. As this issue was very general, I may close it in a few days if I have no return from you. It would be interesting to create a more specific issue for TTS. So, let me know!

**Comment by chaosarium** [comment]
Hi @HugoFara!

I checked out the latest version (2.2.0) and saw the changes that you've made. I like the success and failure sounds! 

I ran into some problem with changing language for previous modification to `tts.php` but I haven't had a chance to look into that yet. As of now my text to speech seems limited to function with the language specified in settings. Right now, I think this issue can be closed.

One problem, however, is that the "Read words aloud" button doesn't stay checked in test mode so everytime the user need to check the box to get pronunciation.

I've also been thinking about some ideas I had for LWT and I will bring them to discussions soon. Hopefully I can have some time to contribute.

**Comment by HugoFara** [comment]
Hi!

Glad to see you appreciate the motivational sounds! 

For the "Read words aloud", in fact it is not saved to settings yet, as we are working on a merge of your changes on ``tts.php``, I consider it an experimental feature, before a more mature system.  

Never hesitate to create issues when you run across problems  ;) In the worst case the resolution may help someone else!
