### ISSUE TITLE
Can't parse japanese text properly

### ISSUE THREAD

**Issue by rc-ops** [HugoFara/lwt#35]
Extracted from #31 

- So before submitting the issue, I realised that I could go to _My Languages_ section and parse from there. It returns some numbers, but I'm not really sure if it's doing anything because If I go the My Texts, there's still no words or any info whatsoever
- This section still returns a notice
`Notice: Undefined variable: 0 in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\lwt\edit_languages.php on line 725`
> ![5](https://user-images.githubusercontent.com/72221896/170506690-3dc4d2b2-6c46-45b9-a485-23f33be0360e.jpg)
- After clicking to parse, still no info about the text.
> ![6](https://user-images.githubusercontent.com/72221896/170507025-e2e1336d-2ebc-4bed-b313-df748b901ec8.jpg)

**Desktop (please complete the following information):**
 - Same setup as last time, except this time Chromium has another version
 - OS: Windows 11 21H2 and Windows 10 20H2
- Browser: Chromium 101.0.4951.64
- EasyPHPDevserver-17 PHP 7.1.3

**Comment by HugoFara** [comment]
I may have fixed the problems, so here is the cause: ``Notice: Undefined variable: 0``. That was caused by the typo ``$$nfcount`` (instead of ``$nfcount`` for "news feed count"). By default, notices and warnings are not displayed on the page on Linux, which is why I missed that.

Once that was fixed, things came back to normal with the UI, so the issues may be related. For the other points you evoked:
- In release 2.4.0, I repaired the My Languages section, which is why you can reparse texts from here.
- For header "sentences deleted : 1701 [...]", it simply indicates that the database was truncated, and then generated again, so everything went smoothly.

I hope this time your Japanese will go well :dango:
