### ISSUE TITLE
DB connect error when use docker 

### ISSUE THREAD

**Issue by gaoxiangluke** [HugoFara/lwt#37]
**Describe the bug**
After I compile and  run docker-compose file, I tried to connect to localhost:8010 but I got an error page saying DB connect error

**To Reproduce**
1. run docker compose file
2. go to  localhost:8010 
**Expected behavior**
lwt page should open 
**Screenshots**
![image](https://user-images.githubusercontent.com/20980567/178130351-822ec5ac-9a2e-438e-a4bc-e6f29ea98360.png)

**Desktop (please complete the following information):**
 - OS: win10 and Ubuntu 20.0 (I tried both, they both have this error)
 - Browser chrome

**Comment by HugoFara** [comment]
Hello, I have been investigating your issue this last three days. The PHP part of LWT is in a container with its own network, and cannot access MariaDB (database part), since it is on another network, so the error message is telling you that no data were received. 

I have been trying to fix it, but I'm not the one who did the Docker part, so it is taking me more time than expected, but I will make it work!

Otherwise, I have no idea of why it worked and does no longer...

**Comment by gaoxiangluke** [comment]
Thank you very much!
