### ISSUE TITLE
Mecab does not work when text have space 

### ISSUE THREAD

**Issue by gaoxiangluke** [HugoFara/lwt#39]
**Describe the bug**
when Japanese text has space in between word, mecab won't parse correctly. 
**To Reproduce**
1. add Japanese with mecab
2. add some japanese text with space for ex "新 し い 物語 が"
3. mecab parse not correctly

**Expected behavior**
mecab should parse correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/20980567/179002837-45690490-e4f3-4403-a74d-48da64c04a73.png)

**Additional context**
Remove spaces manually does fix it. So I suspect text got inserted into mecab before space is removed. This problem is probably not a priority, since preprocessing text with a website like this [[https://onlinetexttools.com/remove-all-whitespace-from-text]] can fix it.

**Comment by HugoFara** [comment]
Hello,

Spaces are important since they have a semantic value (they change the meaning of a sentence). I'm not sure why your text has such spaces, but I cannot develop a script to remove them, since they would be required for some users. So in the end, it's only a formatting issue relative to your text, not something LWT can solve.

Hope you will enjoy you Japanese practice, またね!
