### ISSUE TITLE
Unclear path for Mobile_Detect.php

### ISSUE THREAD

**Issue by chaosarium** [HugoFara/lwt#5]
**Describe the bug**
Reading a text might result in this error:
```
[Mon Jan 10 17:40:52 2022] PHP 7.4.12 Development Server (http://localhost:9004) started
[Mon Jan 10 17:40:54 2022] [::1]:53495 Accepted
[Mon Jan 10 17:40:54 2022] [::1]:53495 [500]: GET /do_text.php?start=1 - require_once(): Failed opening required 'vendor/mobiledetect/mobiledetectlib/Mobile_Detect.php' (include_path='.:/Applications/MAMP/bin/php/php7.4.12/lib/php') in /Users/username/vendor/hugofara/lwt/do_text.php on line 15
[Mon Jan 10 17:40:54 2022] [::1]:53495 Closing
```

**To Reproduce**
(I'm not sure if this is the proper way to set up lwt. But since MAMP doesn't come with composer, I followed [this](https://stackoverflow.com/questions/30324042/installing-composer-on-osx-with-mamp) guide and put `composer.phar` in `~/`
1. `composer require hugofara/lwt`
2. Start PHP development server from VSCode. Everything seems to work fine until making a request to `do_text.php` or `do_test.php` 
3. Read a text, which results in a blank web page

**Expected behavior**
lwt automatically finds the right `Mobile_Detect.php`.

**Screenshots**
Essentially blank web page:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/38693485/148746549-73e14edb-59b3-43ae-b7bd-9c79af12ede7.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1
 - Browser: Safari
 - PHP 7.4.12  
 - MySQL 5.7.32

**Additional context**
Specifying the absolute path to `Mobile_Detect.php` fixes the issue, but I'm sure this isn't the most elegant solution.
```
require_once '/Users/username/vendor/mobiledetect/mobiledetectlib/Mobile_Detect.php'; // (was 'vendor/mobiledetect/mobiledetectlib/Mobile_Detect.php';)
```
Since composer installs both `mobiledetect/mobiledetectlib` and `hugofara/lwt` in `vendor/`, this also works
```
require_once '../../mobiledetect/mobiledetectlib/Mobile_Detect.php'; // (was 'vendor/mobiledetect/mobiledetectlib/Mobile_Detect.php';)
```

**Comment by HugoFara** [comment]
Hello!

Apparently I went a bit too fast with issue #4 . Composer isn't guilty here: the command I suggest in the README (``composer require``) is wrong.

## Problem 
``composer require`` is usually used for packages you want to include in another project (API for instance). However, LWT is an application. It installs LWT in the ``vendor/`` folder, which **breaks all paths**.

## Solution
Use ``composer create-project hugofara/lwt``. It will create a folder with the same organization is in the git.

## In the future
With v2.1.0, I have more or less finished reorganizing the code. Now I will continue developing tests, so that I won't miss this kind of obvious issue. Until then, thank you for your contribution!
