### ISSUE TITLE
Add userid to languages table, login screen to choose user, and possibly remove global $tbpref

### ISSUE THREAD

**Issue by jzohrab** [HugoFara/lwt#50]
Currently I believe that global $tbpref is used to allow for multiple users to use the same database, but that makes queries more complicated to write, and won't let devs use stored procedures or queries (which are easier to test).

If a user table is added, and the user specified on app startup (and stored in the session), the languages table could have a userId field added, which would keep all texts, words, and terms separate per user.

**Comment by HugoFara** [comment]
Hi! 

I think what you are proposing is interesting, but it would include a major rewriting of LWT, which is not something I'm trying to do currently, as explained in discussion #36 .

However, this is definitely a thing I want for the "LW2" project, as I'm aiming to get closer to the standards. In the meantime, here are several solutions:
* LWT can use the WordPress identification system ([docs/wordpress.md](https://github.com/HugoFara/lwt/tree/master/docs/wordpress.md)), I believe it to be the only way to edit the ``$tbpref`` value.
* The "refactor" branch of [hans/lwt](https://github.com/hans/lwt/tree/refactor) tries to include better PHP standards, it can be interesting to get some inspiration, but not sure you want to use this 10-year-old branch.

Hope it can help you, otherwise, I'm looking for comment, advice and contributor for the new LWT project, so thanks for sharing your thoughts!
