### ISSUE TITLE
Tests should not use sentences with unknown words

### ISSUE THREAD

**Issue by jzohrab** [HugoFara/lwt#52]
**Description**

I imported a long text and started working through terms.  When it came to testing, the test routine used sentences with many unknown words, which was confusing.  We should limit the tests to only use sentences where all words are at least status <> unknown.

**Comment by HugoFara** [comment]
Hello!

Thanks for signalling this issue. From what I have been testing, it can be annoying sentences that contain only 1 unknown word, because it really limits the number of testable sentences. So what I've been working on is to test sentences that contain at least 70% of known words, so that you can test words in a meaningful context, even if you don't understand every single word.

Actually there was a code already trying to select sentences with known words, but it was not working, so I removed it. I hope you will enjoy this new feature!
