### ISSUE TITLE
Tests now sometimes only show single word, not complete sentence

### ISSUE THREAD

**Issue by jzohrab** [HugoFara/lwt#64]
Given the following text:

![image](https://user-images.githubusercontent.com/1637133/200152662-8807420b-9f20-4cd0-97ed-01d0904aacf7.png)

Running the tests for this text gives me the following:

![image](https://user-images.githubusercontent.com/1637133/200152701-34a57e5c-3dd2-46e2-8d07-175bd0d83c28.png)

The test should show the complete sentence, not just single terms.  Investigating.

**Comment by jzohrab** [comment]
// The problem is the new query in do_test_test.php;

```
SELECT DISTINCT SeID, UnknownRate
    FROM sentences
    JOIN (
        SELECT total.Ti2SeID, UnknownWords / TotalWords AS UnknownRate
        FROM (
            -- A ---------
            SELECT Ti2SeID, COUNT(*) AS UnknownWords
            FROM textitems2
            WHERE Ti2WordCount = 1 AND Ti2WoID = 0
            GROUP BY Ti2SeID
        ) AS unknowns
        JOIN (
            -- B ---------
            SELECT Ti2SeID, COUNT(*) AS TotalWords
            FROM textitems2
            WHERE Ti2WordCount = 1
            GROUP BY Ti2SeID
        ) AS total
        ON unknowns.Ti2SeId = total.Ti2SeId
    ) AS ti_with_rate 
    ON SeID = ti_with_rate.Ti2SeID
```

If a sentence has 0 unknowns, then the `unknowns` query will return empty set, and since that's joined with the `total` it will return no sentences where there are 0 unknowns.  This query can be simplified, I'll open a PR against master and will submit it.

**Comment by HugoFara** [comment]
Actually this is an expected behavior, here is the logic:
* Term "term" has to be tested
* The only sentence(s) containing it have too many unknown terms (meaningless sentence).
* Two approaches here:
  * Solution 1: output the meaningless sentence with the term
  * Solution 2 is to output only the term alone, which I went for. 
 
I'm not sure if there is a best solution between meaningless sentence/no sentence though. I'm open to discussion.

I will still have a look at your pull request, at least because it simplifies the SQL query.

**Comment by HugoFara** [comment]
Erratum: your pull request was about sentences not showed when then should be. It's a real bug and not an implementation discussion. It is now fixed, thanks for your pull request!
