### ISSUE TITLE
Question on WordPress integration for @Redmattski

### ISSUE THREAD

**Issue by jzohrab** [HugoFara/lwt#72]
Hi @Redmattski - I saw issue #41 that you had opened, hopefully you will see this open issue and will reply.   (You don't have a fork of this repo, otherwise I would have pinged you there.)

I was curious how you were using LWT and Wordpress together.  I've been hacking on LWT a bit and there are some things about the integration with WP that make LWT development more difficult than it needs to be.  If we can remove the WordPress integration, we might be able simplify a few things in this project and make it easier to work with.

Can you let me know how you're using both of these things?  Do you have multiple people using the same LWT database, or is it just you?

Cheers, jz

**Comment by jzohrab** [comment]
I'll close this in a week or so if he doesn't respond.

**Comment by Redmattski** [comment]
Hi JZ

Thanks for reaching out.  The WordPress setup with LWT provides two functions that are important for me:

- Multi user setup without the need for separate instances of LWT (I have a small instance for my family)

- Password login via LDAP.  My site is exposed to the Internet so currently WordPress carries out the authentication and authorisation.  I have extended WordPress to link to my LDAP instance.

I hope this helps explain my use case.   Let me know if you have any further questions.

Cheers

Matthew



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: JZ ***@***.***>
Sent: Wednesday, November 9, 2022 5:07:47 AM
To: HugoFara/lwt ***@***.***>
Cc: Redmattski ***@***.***>; Mention ***@***.***>
Subject: [HugoFara/lwt] Question on WordPress integration for @Redmattski (Issue #72)


Hi @Redmattski<https://github.com/Redmattski> - I saw issue #41<https://github.com/HugoFara/lwt/issues/41> that you had opened, hopefully you will see this open issue and will reply. (You don't have a fork of this repo, otherwise I would have pinged you there.)

I was curious how you were using LWT and Wordpress together. I've been hacking on LWT a bit and there are some things about the integration with WP that make LWT development more difficult than it needs to be. If we can remove the WordPress integration, we might be able simplify a few things in this project and make it easier to work with.

Can you let me know how you're using both of these things? Do you have multiple people using the same LWT database, or is it just you?

Cheers, jz

**Comment by jzohrab** [comment]
I've proposed a very small code change in https://github.com/HugoFara/lwt/pull/76 that will _vastly_ simplify this code.

@Redmattski, if we do merge in that change (which we should, IMO), **and** you choose to upgrade your LWT release, you'll need to split your LWT database into separate databases for each user, as outlined in that pull request.  Hope that's not massively onerous, but the current code is pretty rough.  Cheers!

**Comment by jzohrab** [comment]
Closing.  I've replaced this on my fork, and Hugo F. will handle it has he will going forward.
