### ISSUE TITLE
Video in the /media folder don't show up in the "or choose a file in" dropdown menu

### ISSUE THREAD

**Issue by chaosarium** [HugoFara/lwt#9]
**Is your feature request related to a problem? Please describe.**
When trying to add videos that are in the /media folder, users have to type in the path manually

**Describe the solution you'd like**
Detect videos in the /media folder and list them in the "choose a file in" menu

**Describe alternatives you've considered**
Have a separate folder for videos?

**Comment by HugoFara** [comment]
Your issue is somehow between a bug and a feature request.

Before 2.0.4-fork, LWT did not support videos. When I added the possibility for online videos, I forgot to add path for local video files (".mp4" for instance), which is why it doesn't work.

Adding ".mp4" in ``selectmediapathoptions`` (``session_utility.php``) would be a quick-fix, but I may want to implement it in a better way: the features of the audio file were not ported to the video files, so it would be the occasion to standardize everything.

**Comment by HugoFara** [comment]
Hello again!

It took more time than expected: jPlayer (the media player library) is abandoned and struggles with HTML5 videos. I pushed changes so that you can add videos, however they will be rendered with a minimal interface. I will have to switch to a more modern media player (for instance [mediaelement](https://github.com/mediaelement/mediaelement)).

I let this issue open until the next release if you have any question or comment!
