### ISSUE TITLE
The RegExp may have bug to separate the words

### ISSUE THREAD

**Issue by 99MengXin** [HugoFara/lwt#91]
**Describe the bug**
The RegExp may have bug to separate the words.

**To Reproduce**
1. Go to `Languages`
2. Click on `Edit` (In this case, English)
3. Scroll down to `RegExp Split Sentences`, and set `.!?:;`
4. Scroll down to `RegExp Word Characters`, and set `\-\'a-zA-ZÀ-ÖØ-öø-ȳЀ-ӹ`
5. Click on `Save`
6. Choose any English text and read
7. See error

**Expected behavior**
e.g. 'I should like it.'
The word `it` in this sentence should be recognized to `it` but `it.` with a period.
In other cases, symbols can be recognized perfectly.
e.g. ?!;:

**Screenshots**
<img width="126" alt="截圖 2023-02-16 08 24 20" src="https://user-images.githubusercontent.com/51739513/219226281-d1aeabae-f9bf-40dc-b860-3c47a84f5f20.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Safari 16.2
 - Firefox 109.0 
 - Brave 1.48.164

**Smartphone (please complete the following information):**
 - iPhone 8
 - iOS8.1 14.8
 - Safari
 - 14

**Additional context**
This function works well in original LWT.

**Comment by HugoFara** [comment]
Hi! Here, I can give you a few suggestions:
In step 4 you detail 
> Scroll down to ``RegExp Word Characters``, and set ``\-\'a-zA-ZÀ-ÖØ-öø-ȳЀ-ӹ``
Base on the provided RegExp, ``'`` should be considered a word, which is useful in some contexts (english genitive such as "Tom's house" → "``Tom's`` + ``house``"). If it's a trouble to you, you can simply remove the apostrophe for words characters (use ``\-a-zA-ZÀ-ÖØ-öø-ȳЀ-ӹ``).

In your context, I would suggest to use ``"`` instead of ``'`` whenever possible.

Finally, I can look into the word parser if I have some time, but it a core function so it's really hard to change without breaking something for users.

I hope that helps you :smile:
