### ISSUE TITLE
2.7 Display Issues

### ISSUE THREAD

**Issue by zenkeku** [HugoFara/lwt#99]
**Describe the bug**
The home page doesn't display correctly.

**To Reproduce**
Go to the home page.

**Expected behavior**
A nice table of links.

**Screenshots**
![Screenshot 2023-03-14 at 9 46 44 AM](https://user-images.githubusercontent.com/6876494/225021790-e344460e-dc2b-4e0c-8cf7-664bd801cf56.png)

**Desktop (please complete the following information):**
 - OS: Mac Ventura 13.3
 - Browser: Microsoft Edge (110.0.1587.69), Safari (16.4 (18615.1.25))

**Smartphone (please complete the following information):** (On Smartphone it displays correctly)
 - Device: iPhone 13 Pro Max
 - OS: iOS 16.3
 - Browser: Safari
 - Version: ?

**Additional context**

**Comment by HugoFara** [comment]
Hi! I think it's just a cache problem. *Reloading cache* should be enough.

**For desktop users**
Hit Ctrl+F5 or Command+F5 (Mac)

**For phone users**
Reload the page in a private window.

Either way, the issue will disappear by itself after some time, it's due to how browsers work, not on LWT side...

**Comment by zenkeku** [comment]
RIP, that worked. Thanks!

**Comment by HugoFara** [comment]
You're welcome :wink:
